<?php
function getNac(){
return [
    "Portugal" => "pt",        // Portugal
    "Brazil" => "br",          // Brasil
    "France" => "fr",          // França
    "Germany" => "de",         // Alemanha
    "Spain" => "es",           // Espanha
    "Italy" => "it",           // Itália
    "England" => "gb-eng",     // Inglaterra (bandeira específica)
    "Scotland" => "gb-sct",    // Escócia
    "Wales" => "gb-wls",       // País de Gales
    "Northern Ireland" => "gb",// Irlanda do Norte
    "Ireland" => "ie",         // Irlanda
    "Argentina" => "ar",       // Argentina
    "Belgium" => "be",         // Bélgica
    "Netherlands" => "nl",     // Países Baixos (Holanda)
    "Senegal" => "sn",         // Senegal
    "Ivory Coast" => "ci",     // Costa do Marfim
    "Ghana" => "gh",           // Gana
    "Nigeria" => "ng",         // Nigéria
    "Australia" => "au",       // Austrália
    "United States" => "us",   // Estados Unidos
    "Canada" => "ca",          // Canadá
    "Sweden" => "se",          // Suécia
    "Denmark" => "dk",         // Dinamarca
    "Norway" => "no",          // Noruega
    "Switzerland" => "ch",     // Suíça
    "Croatia" => "hr",         // Croácia
    "Poland" => "pl",          // Polônia
    "Serbia" => "rs",          // Sérvia
    "Republic of Ireland" => "ie",         // Irlanda (República da Irlanda)
    "Czech Republic" => "cz",  // República Tcheca
    "Austria" => "at",         // Áustria
    "Japan" => "jp",           // Japão
    "South Korea" => "kr",     // Coreia do Sul
    "Mexico" => "mx",          // México
    "Colombia" => "co",        // Colômbia
    "Uruguay" => "uy",         // Uruguai
    "Chile" => "cl",           // Chile
    "Paraguay" => "py",        // Paraguai
    "Peru" => "pe",            // Peru
    "Venezuela" => "ve",       // Venezuela
    "Ecuador" => "ec",         // Equador
    "Bolivia" => "bo",         // Bolívia
    "Guyana" => "gy",          // Guiana
    "Suriname" => "sr",        // Suriname
    "Belize" => "bz",          // Belize
    "Costa Rica" => "cr",      // Costa Rica
    "Honduras" => "hn",        // Honduras
    "Panama" => "pa",          // Panamá
    "Guatemala" => "gt",       // Guatemala
    "El Salvador" => "sv",     // El Salvador
    "Nicaragua" => "ni",       // Nicarágua
    "Bermuda" => "bm",         // Bermudas
    "Bahrain" => "bh",         // Bahrein
    "Kuwait" => "kw",          // Kuwait
    "Qatar" => "qa",           // Catar
    "Finland" => "fi",  // Finlândia
    "Bosnia and Herzegovina" => "ba",  // Bósnia e Herzegovina
    "United Arab Emirates" => "ae", // Emirados Árabes Unidos
    "Saudi Arabia" => "sa",    // Arábia Saudita
    "Oman" => "om",            // Omã
    "Yemen" => "ye",           // Iémen
    "Jordan" => "jo",          // Jordânia
    "Lebanon" => "lb",         // Líbano
    "Syria" => "sy",           // Síria
    "Iraq" => "iq",            // Iraque
    "Egypt" => "eg",           // Egito
    "Israel" => "il",          // Israel
    "Palestine" => "ps",       // Palestina
    "Turkey" => "tr",          // Turquia
    "Iran" => "ir",            // Irã
    "Afghanistan" => "af",     // Afeganistão
    "India" => "in",           // Índia
    "Pakistan" => "pk",        // Paquistão
    "Sri Lanka" => "lk",       // Sri Lanka
    "Nepal" => "np",           // Nepal
    "Bangladesh" => "bd",      // Bangladesh
    "Bhutan" => "bt",          // Butão
    "Maldives" => "mv",        // Maldivas
    "Myanmar" => "mm",         // Myanmar (Birmânia)
    "Thailand" => "th",        // Tailândia
    "Vietnam" => "vn",         // Vietnã
    "Cambodia" => "kh",        // Camboja
    "Laos" => "la",            // Laos
    "Malaysia" => "my",        // Malásia
    "Singapore" => "sg",       // Singapura
    "Indonesia" => "id",       // Indonésia
    "Philippines" => "ph",     // Filipinas
    "Senegal" => "sn",         // Senegal 
    "Cameroon" => "cm",        // Camarões
    "Brunei" => "bn",          // Brunei
    "Ukraine" => "ua",         // Ucrânia
    "South Africa" => "za",    // África do Sul
    "Botswana" => "bw",        // Botswana
    "Lesotho" => "ls",         // Lesoto
    "Swaziland" => "sz",       // Suazilândia (Eswatini)
    "Namibia" => "na",         // Namíbia
    "Zimbabwe" => "zw",        // Zimbábue
    "Mozambique" => "mz",      // Moçambique
    "Angola" => "ao",          // Angola
    "Zambia" => "zm",          // Zâmbia
    "Malawi" => "mw",          // Maláui
    "Tanzania" => "tz",        // Tanzânia
    "Rwanda" => "rw",          // Ruanda
    "Burundi" => "bi",         // Burundi
    "Uganda" => "ug",          // Uganda
    "Kenya" => "ke",           // Quênia
    "Ethiopia" => "et",        // Etiópia
    "Somalia" => "so",         // Somália
    "Madagascar" => "mg",      // Madagascar
    "Mauritius" => "mu",       // Maurício
    "Seychelles" => "sc",      // Seicheles
    "Comoros" => "km",         // Comores
    "Réunion" => "re",         // Reunião
    "Mayotte" => "yt",         // Mayotte
    "Fiji" => "fj",            // Fiji
    "Tonga" => "to",           // Tonga
    "Samoa" => "ws",           // Samoa
    "Solomon Islands" => "sb", // Ilhas Salomão
    "Vanuatu" => "vu",         // Vanuatu
    "Guinea" => "pg",          // Papua-Nova Guiné
    "New Zealand" => "nz",     // Nova Zelândia
    "Cook Islands" => "ck",    // Ilhas Cook
    "Niue" => "nu",            // Niue
    "Greece" => "gr",  // Grécia
    "Algeria" => "dz",  // Argélia
    "Morocco" => "ma",  // Marrocos
    "Mali" => "ml",     // Mali
    "Tokelau" => "tk",         // Tokelau
    "American Samoa" => "as",  // Samoa Americana
    "French Polynesia" => "pf",// Polinésia Francesa
    "Wallis and Futuna" => "wf", // Wallis e Futuna
    "New Caledonia" => "nc",   // Nova Caledônia
    "Tahiti" => "pf",          // Taiti
    "Easter Island" => "cl",   // Ilha de Páscoa
    "Greenland" => "gl",       // Groenlândia
    "Iceland" => "is",         // Islândia
    "Faroe Islands" => "fo",   // Ilhas Faroe
    "Saint Helena" => "sh",    // Santa Helena
    "Ascension Island" => "ac",// Ilha Ascensão
    "Tristan da Cunha" => "tc" // Tristão da Cunha
        ];
    }
        ?>